<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <?php
        $this->headLink()->prependStylesheet(
                $this->baseUrl() . '/css/blueprint/screen.css', 'screen');
        ?>
        <?php
        $this->headLink()->prependStylesheet(
                $this->baseUrl() . '/css/blueprint/print.css', 'print');
        ?>
        <?php
        $this->headLink()->prependStylesheet(
                $this->baseUrl() . '/css/blueprint/ie.css', 'screen', 'IE');
        ?>
        <?php
        $this->headLink()->prependStylesheet(
                $this->baseUrl() . '/css/blueprint/master.css', 'screen');
        ?>
        <?php echo $this->headLink(); ?>


    </head>
    <div id="wrapper">

        <header id="header">
            <h3>Quick-Start</h3>
        </header>
        <div id="bar"><h4><?php echo $this->title; ?></h4></div>

        <section id="middle">
 
            <div id="container">
                <div id="content">
                    <?php echo $this->layout()->content; ?>
                </div>


            </div>

            <aside id="sideLeft">
                <h3>Меню</h3> 
                <?php if ($this->identity): ?>
                    <h4>Вы зашли как <?php echo $this->identity->username; ?></h4>
                    
                <?php else: ?>
                    <p><?php echo $this->error ?></p>
                    <?php echo $this->form; ?>
                    <p><a href="<?php echo $this->url(array('controller' => 'users',
                        'action' => 'registration')); ?>">Регистрация</a></p>
                <?php endif ?>


            </aside>

        </section>

    </div>
    <div id="footer" align="center">
        <strong>Footer:</strong> </div>
</html>